"""Fixed-step simulation scheduling and frame-pacing diagnostics."""

from __future__ import annotations

import math
from collections import deque
from dataclasses import dataclass
from typing import Iterable


@dataclass(frozen=True)
class FramePlan:
    """Simulation work generated by one rendered frame."""

    simulation_steps: int
    interpolation_alpha: float
    accepted_seconds: float
    dropped_seconds: float


class FramePacingMonitor:
    """Bounded frame-time history suitable for diagnostics and playtest evidence."""

    def __init__(self, history_size: int = 600, hitch_seconds: float = 1.0 / 30.0) -> None:
        if history_size < 1:
            raise ValueError("history_size must be positive")
        if hitch_seconds <= 0:
            raise ValueError("hitch_seconds must be positive")
        self._frames: deque[float] = deque(maxlen=history_size)
        self.hitch_seconds = float(hitch_seconds)
        self.total_frames = 0
        self.total_hitches = 0
        self.total_dropped_seconds = 0.0
        self.maximum_seconds = 0.0

    def record(self, frame_seconds: float, dropped_seconds: float = 0.0) -> None:
        if not math.isfinite(frame_seconds) or frame_seconds < 0:
            raise ValueError("frame_seconds must be finite and non-negative")
        if not math.isfinite(dropped_seconds) or dropped_seconds < 0:
            raise ValueError("dropped_seconds must be finite and non-negative")
        self._frames.append(frame_seconds)
        self.total_frames += 1
        self.total_dropped_seconds += dropped_seconds
        if frame_seconds > self.hitch_seconds:
            self.total_hitches += 1
        if frame_seconds > self.maximum_seconds:
            self.maximum_seconds = frame_seconds

    @staticmethod
    def _percentile(sorted_values: list[float], fraction: float) -> float:
        if not sorted_values:
            return 0.0
        position = (len(sorted_values) - 1) * fraction
        lower = int(position)
        upper = min(len(sorted_values) - 1, lower + 1)
        weight = position - lower
        return sorted_values[lower] * (1.0 - weight) + sorted_values[upper] * weight

    def snapshot(self) -> dict[str, float | int]:
        values = sorted(self._frames)
        return {
            "sample_count": len(values),
            "total_frames": self.total_frames,
            "hitch_count": self.total_hitches,
            "hitch_ratio": self.total_hitches / self.total_frames if self.total_frames else 0.0,
            "p50_ms": self._percentile(values, 0.50) * 1000.0,
            "p95_ms": self._percentile(values, 0.95) * 1000.0,
            "p99_ms": self._percentile(values, 0.99) * 1000.0,
            "maximum_ms": self.maximum_seconds * 1000.0,
            "dropped_ms": self.total_dropped_seconds * 1000.0,
        }

    def samples(self) -> tuple[float, ...]:
        return tuple(self._frames)


class FixedStepScheduler:
    """Convert real frame time into deterministic fixed simulation steps."""

    def __init__(
        self,
        simulation_hz: int = 60,
        max_catch_up_steps: int = 5,
        max_frame_seconds: float = 0.25,
        monitor: FramePacingMonitor | None = None,
    ) -> None:
        if simulation_hz < 1:
            raise ValueError("simulation_hz must be positive")
        if max_catch_up_steps < 1:
            raise ValueError("max_catch_up_steps must be positive")
        if max_frame_seconds <= 0:
            raise ValueError("max_frame_seconds must be positive")
        self.simulation_hz = simulation_hz
        self.step_seconds = 1.0 / simulation_hz
        self.max_catch_up_steps = max_catch_up_steps
        self.max_frame_seconds = float(max_frame_seconds)
        self.accumulator = 0.0
        self.total_simulation_steps = 0
        self.monitor = monitor or FramePacingMonitor()

    def plan(self, elapsed_seconds: float) -> FramePlan:
        if not math.isfinite(elapsed_seconds) or elapsed_seconds < 0:
            raise ValueError("elapsed_seconds must be finite and non-negative")

        accepted = min(float(elapsed_seconds), self.max_frame_seconds)
        dropped = max(0.0, float(elapsed_seconds) - accepted)
        self.accumulator += accepted

        available_steps = int((self.accumulator + 1e-12) / self.step_seconds)
        simulation_steps = min(available_steps, self.max_catch_up_steps)
        self.accumulator -= simulation_steps * self.step_seconds

        if available_steps > self.max_catch_up_steps:
            overflow_steps = available_steps - self.max_catch_up_steps
            overflow_seconds = overflow_steps * self.step_seconds
            dropped += overflow_seconds
            self.accumulator -= overflow_seconds

        if self.accumulator < 0:
            self.accumulator = 0.0
        elif self.accumulator >= self.step_seconds:
            retained_steps = int(self.accumulator / self.step_seconds)
            retained_seconds = retained_steps * self.step_seconds
            self.accumulator -= retained_seconds
            dropped += retained_seconds

        self.total_simulation_steps += simulation_steps
        alpha = self.accumulator / self.step_seconds
        self.monitor.record(float(elapsed_seconds), dropped)
        return FramePlan(simulation_steps, alpha, accepted, dropped)

    def replay(self, frame_seconds: Iterable[float]) -> list[FramePlan]:
        return [self.plan(value) for value in frame_seconds]
